# Generated by Django 6.0.6 on 2026-06-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_lesson_video_link"),
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payments",
            new_name="Payment",
        ),
    ]
